/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Component;
import java.util.Arrays;
import javax.swing.JOptionPane;



/**
 *
 * @author CHEN
 */
public class login extends javax.swing.JFrame {
login l;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        l=this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprin = new javax.swing.JPanel();
        label_contrasenia = new javax.swing.JLabel();
        text_usuario = new javax.swing.JTextField();
        label_usuario1 = new javax.swing.JLabel();
        text_contrasenia = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnentrar = new javax.swing.JButton();
        btnregistro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelprin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_contrasenia.setText("Contraseña");
        panelprin.add(label_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, 30));

        text_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usuarioActionPerformed(evt);
            }
        });
        panelprin.add(text_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 210, 20));

        label_usuario1.setText("   Usuario");
        panelprin.add(label_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 60, 30));

        text_contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_contraseniaActionPerformed(evt);
            }
        });
        panelprin.add(text_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, -1));

        btnentrar.setText("entrar");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });

        btnregistro.setText("registro");
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("olvidaste tu contraseña");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnentrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnregistro)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(106, 106, 106))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnentrar)
                    .addComponent(btnregistro))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelprin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 340, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprin, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usuarioActionPerformed
        // usuario
    }//GEN-LAST:event_text_usuarioActionPerformed

    private void text_contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_contraseniaActionPerformed
        // contrasenia
    }//GEN-LAST:event_text_contraseniaActionPerformed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        // boton entrar
        //recoger la contra introducida
       char[] input =text_contrasenia.getPassword();
       String user =text_usuario .getText();
       if(isUserCorrect(user,input)){
           
       JOptionPane.showMessageDialog(panelprin,"Usuario correcto");
       }else{
      
       JOptionPane.showMessageDialog(panelprin,"Usuario o contraseña incorrecta",
       "ERROR",
     JOptionPane.ERROR_MESSAGE);
       }
      
    }//GEN-LAST:event_btnentrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        // boton registro
        //nueva ventana de reegistro
        Registro r= new Registro(l);
        r.setVisible (true);
        l.setVisible(false);
        
    }//GEN-LAST:event_btnregistroActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JButton btnregistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_contrasenia;
    private javax.swing.JLabel label_usuario1;
    private javax.swing.JPanel panelprin;
    private javax.swing.JPasswordField text_contrasenia;
    private javax.swing.JTextField text_usuario;
    // End of variables declaration//GEN-END:variables

    private boolean isUserCorrect(String user, char[] input) {
         boolean isCorrect =true;
char[] correctPassword ={'1','2','3'};
String correctUser="paco";

if((input.length !=correctPassword.length)||(user.length()!=correctUser.length())){
isCorrect = false;
} else{
if(Arrays.equals(input, correctPassword)&& (correctUser.equals(user))) isCorrect =true;
else isCorrect =false;

}
        return isCorrect;
    }
}
