/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author CHEN
 */
public class menu_profesor extends javax.swing.JFrame {

    /**
     * Creates new form menu_profesor
     */
    public menu_profesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btncancelarprof = new javax.swing.JButton();
        btnconsultapro1 = new javax.swing.JButton();
        btncejemp1 = new javax.swing.JButton();
        btnsolipro1 = new javax.swing.JButton();
        btnhistopro1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("       Bienvenido Profesor ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 24, 152, 29));

        btncancelarprof.setText("cancelar");
        btncancelarprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarprofActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelarprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 259, 92, -1));

        btnconsultapro1.setText("consulta de documentos");
        jPanel1.add(btnconsultapro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 71, 194, -1));

        btncejemp1.setText("consulta de ejemplares");
        btncejemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncejemp1ActionPerformed(evt);
            }
        });
        jPanel1.add(btncejemp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 112, 194, -1));

        btnsolipro1.setText("solicitud de prestamos");
        btnsolipro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsolipro1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsolipro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 163, 194, -1));

        btnhistopro1.setText("historial de prestamos");
        btnhistopro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistopro1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnhistopro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 216, 194, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 329));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarprofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarprofActionPerformed

    private void btncejemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncejemp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncejemp1ActionPerformed

    private void btnsolipro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsolipro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsolipro1ActionPerformed

    private void btnhistopro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistopro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhistopro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_profesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelarprof;
    private javax.swing.JButton btncejemp1;
    private javax.swing.JButton btnconsultapro1;
    private javax.swing.JButton btnhistopro1;
    private javax.swing.JButton btnsolipro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
