/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author CHEN
 */
public class menu_administrador extends javax.swing.JFrame {

    /**
     * Creates new form menu_administrador
     */
    public menu_administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btncancelarad = new javax.swing.JButton();
        btngestion1 = new javax.swing.JButton();
        btngestion2 = new javax.swing.JButton();
        btnrejemplares1 = new javax.swing.JButton();
        btnconfi1 = new javax.swing.JButton();
        btnconsultas1 = new javax.swing.JButton();
        btnreportes1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("        Bienvenido administrador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 14, 193, 24));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelarad.setText("cancelar");
        btncancelarad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelaradActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelarad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 314, 91, -1));

        btngestion1.setText("gestion de ususarios");
        btngestion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestion1ActionPerformed(evt);
            }
        });
        jPanel1.add(btngestion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 50, 226, -1));

        btngestion2.setText("registro de documentos");
        btngestion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestion2ActionPerformed(evt);
            }
        });
        jPanel1.add(btngestion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 97, 226, -1));

        btnrejemplares1.setText("registro de ejemplares");
        btnrejemplares1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrejemplares1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnrejemplares1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 138, 226, -1));

        btnconfi1.setText("configuracion del sistema");
        btnconfi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfi1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnconfi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 179, 226, -1));

        btnconsultas1.setText("consultas generales");
        btnconsultas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultas1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnconsultas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 223, 226, -1));

        btnreportes1.setText("reportes");
        btnreportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportes1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnreportes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 264, 226, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelaradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelaradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelaradActionPerformed

    private void btngestion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngestion1ActionPerformed

    private void btngestion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngestion2ActionPerformed

    private void btnrejemplares1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrejemplares1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrejemplares1ActionPerformed

    private void btnconfi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfi1ActionPerformed

    private void btnconsultas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconsultas1ActionPerformed

    private void btnreportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelarad;
    private javax.swing.JButton btnconfi1;
    private javax.swing.JButton btnconsultas1;
    private javax.swing.JButton btngestion1;
    private javax.swing.JButton btngestion2;
    private javax.swing.JButton btnrejemplares1;
    private javax.swing.JButton btnreportes1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
