/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author CHEN
 */
public class Registro extends javax.swing.JFrame {
//ventana de login 
    login lpadre;
    
 //ventana de registro 
    Registro r;
    
    /**
     * Creates new form Registro
     * @param l
     */
    public Registro(login l) {
        initComponents();
        lpadre =l;
        r=this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelprin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrimerA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSegundoA = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnregistrarme = new javax.swing.JButton();
        txtcancelar = new javax.swing.JButton();
        txtcontra2 = new javax.swing.JPasswordField();
        txtcontra1 = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelprin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("    edad");
        panelprin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 60, -1));

        txtedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtedadActionPerformed(evt);
            }
        });
        panelprin.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 240, -1));

        jLabel3.setText("Primer Apellido");
        panelprin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 90, -1));

        txtPrimerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerAActionPerformed(evt);
            }
        });
        panelprin.add(txtPrimerA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, -1));

        jLabel4.setText("Segundo Apellido");
        panelprin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 100, -1));

        txtSegundoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoAActionPerformed(evt);
            }
        });
        panelprin.add(txtSegundoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 240, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 240, -1));

        jLabel7.setText("Primer Apellido");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 240, -1));

        jLabel8.setText("Segundo Apellido");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 240, -1));

        jLabel9.setText("Primer Apellido");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 240, -1));

        panelprin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jLabel15.setText("Rol");
        panelprin.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 37, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Alumno", "Profesor" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        panelprin.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 240, -1));

        jLabel10.setText("usuario");
        panelprin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 60, -1));

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        panelprin.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 240, -1));

        jLabel11.setText("contraseña");
        panelprin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 80, -1));

        jLabel12.setText("repetir contraseña");
        panelprin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 110, -1));

        btnregistrarme.setText("registarme");
        btnregistrarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarmeActionPerformed(evt);
            }
        });

        txtcancelar.setText("cancelar");
        txtcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnregistrarme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(txtcancelar)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregistrarme)
                    .addComponent(txtcancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelprin.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 240, 60));

        txtcontra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontra2ActionPerformed(evt);
            }
        });
        panelprin.add(txtcontra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 240, -1));

        txtcontra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontra1ActionPerformed(evt);
            }
        });
        panelprin.add(txtcontra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprin, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrimerAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerAActionPerformed

    private void txtSegundoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoAActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btnregistrarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarmeActionPerformed
        // TODO add your handling code here:
        //comprobacion de llenado de campos
        String nombre =txtNombre .getText();
        String primerA =txtPrimerA.getText();
        String segundoA = txtSegundoA.getText();
        String edad=txtedad.getText();
        String usuario =txtusuario.getText();
        char[]contrasenia =txtcontra1.getPassword();
        char[] contra2 =txtcontra2.getPassword();
        
        if((nombre.length()<=0) ||(primerA.length()<=0) ||(segundoA.length()<=0) ||(edad.length()<=0) ||(usuario.length()<=0)) {
        JOptionPane.showMessageDialog(panelprin,"Falta rellenar un campo",
       "ERROR",
     JOptionPane.ERROR_MESSAGE);
        }else {
        if(!Arrays.equals(contrasenia,contra2)){
        JOptionPane.showMessageDialog(panelprin,"Las contraseñas no coinciden ",
       "ERROR",
     JOptionPane.ERROR_MESSAGE);
        }
        }
        
        
    }//GEN-LAST:event_btnregistrarmeActionPerformed

    private void txtcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcancelarActionPerformed
        // TODO add your handling code here:
        lpadre.setVisible(true);
        r.setVisible(false);
    }//GEN-LAST:event_txtcancelarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtedadActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtcontra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontra2ActionPerformed

    private void txtcontra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontra1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrarme;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel panelprin;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrimerA;
    private javax.swing.JTextField txtSegundoA;
    private javax.swing.JButton txtcancelar;
    private javax.swing.JPasswordField txtcontra1;
    private javax.swing.JPasswordField txtcontra2;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
